name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
      additional_assets:
        description: "Include additional binary assets in the release"
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  build_assets:
    name: build goversion-select binaries
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version-file: tools/goversion-select/go.mod
          cache: true

      - name: cross-compile goversion-select
        run: |
          mkdir -p ./upload-assets
          ASSETS_DIR="$PWD/upload-assets" .github/workflows/script/cross-compile-goversion-select

      - uses: actions/upload-artifact@v4
        with:
          name: additional-release-assets
          path: upload-assets/

  release:
    needs: build_assets
    permissions:
      actions: read
      id-token: write
      contents: write

    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@v1
    with:
      tag: "${{ github.event.inputs.tag }}"
      additional_assets: ${{ inputs.additional_assets }}
